export const GET_CONTACTS = "GET_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";

export const CHECK_LOGIN = "CHECK_LOGIN";
export const LES_PROFESSEURS = "LES_PROFESSEURS";
export const LES_RESPONSABLES = "LES_RESPONSABLES";
export const AJOUTER_PROFESSEURS_GREVE = "AJOUTER_PROFESSEURS_GREVE";
export const SUPPRIMER_PROFESSEURS_GREVE = "SUPPRIMER_PROFESSEURS_GREVE";
export const AJOUTER_RESPONSABLES_GREVE = "AJOUTER_RESPONSABLES_GREVE";
export const SUPPRIMER_RESPONSABLES_GREVE = "SUPPRIMER_RESPONSABLES_GREVE";

export const APPLIQUER_MANIFESTANTS_GREVE = "APPLIQUER_MANIFESTANTS_GREVE";

export const IS_THERE_A_STRICK = "IS_THERE_A_STRICK";

export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const GET_ALL_ECOLE = "GET_ALL_ECOLE";
export const PEOPLE_WHO_STROCK = "PEOPLE_WHO_STROCK";
export const ADD_GREVE = "ADD_GREVE";
export const IS_THERE_A_STRICK_WITH_DATE = "IS_THERE_A_STRICK_WITH_DATE";
